"""initial schema

Revision ID: a5dcb473a661
Revises: 
Create Date: 2026-09-02 04:55:28.490226+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a5dcb473a661'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anchored_at', sa.DateTime(), nullable=False),
    sa.Column('last_audit_id', sa.Integer(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_anchors'))
    )
    op.create_table('audit_chain_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_id', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_chain_head'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.Enum('LOGIN', 'LOGIN_FAILED', 'SEARCH', 'GRAPH_EXPAND', 'DOC_VIEW', 'DOC_UPLOAD', 'MERGE', 'MERGE_REJECT', 'PATTERN_REVIEW', 'EXPORT', 'ACCESS_REQUEST', 'ACCESS_APPROVAL', 'QUARANTINE_RELEASE', 'CONFIG_CHANGE', name='audit_action_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_resource', sa.Text(), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('jurisdiction_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_row_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_audit_logs_timestamp', ['timestamp'], unique=False)

    op.create_table('document_stage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_stage_events'))
    )
    with op.batch_alter_table('document_stage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_stage_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_stage_events_doc_id'), ['doc_id'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'QUARANTINED', name='job_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=80), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_doc_id'), ['doc_id'], unique=False)

    op.create_table('pattern_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pattern_config')),
    sa.UniqueConstraint('key', name=op.f('uq_pattern_config_key'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('badge_number', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'INVESTIGATOR', 'ADMIN', name='role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('badge_number', name=op.f('uq_users_badge_number'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_jurisdiction', ['jurisdiction_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'CLOSED', name='case_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('read_only_at', sa.DateTime(), nullable=True, comment='DPDP retention: closed cases become read-only after 90 days (PRD 12.3)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cases_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('case_number', name=op.f('uq_cases_case_number'))
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_jurisdiction_id'), ['jurisdiction_id'], unique=False)

    op.create_table('detected_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_type', sa.Enum('STRUCTURING', 'BURNER_PHONE', 'RAPID_MOVEMENT', 'NETWORK_BRIDGE', name='pattern_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entity_keys', sa.JSON(), nullable=False),
    sa.Column('evidence_doc_ids', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'DISMISSED', 'ESCALATED', name='pattern_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_detected_patterns_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detected_patterns'))
    )
    with op.batch_alter_table('detected_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_patterns_case_id'), ['case_id'], unique=False)

    op.create_table('entity_resolution_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source_node_key', sa.String(length=64), nullable=False),
    sa.Column('target_node_key', sa.String(length=64), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('match_basis', sa.Enum('NAME_FUZZY', 'PHONE_PARTIAL', 'PHOTO_SIMILARITY', 'ALIAS_CO_MENTION', name='match_basis', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidence_doc_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MERGED', 'REJECTED', name='resolution_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status <> 'PENDING' OR resolved_by IS NULL", name=op.f('ck_entity_resolution_queue_ck_erq_pending_unresolved')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_entity_resolution_queue_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_resolution_queue'))
    )
    with op.batch_alter_table('entity_resolution_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_resolution_queue_case_id'), ['case_id'], unique=False)

    op.create_table('jurisdiction_access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('target_jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', name='access_request_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_jurisdiction_access_requests_approved_by_users')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_jurisdiction_access_requests_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction_access_requests'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)

    op.create_table('case_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.Enum('FIR', 'CDR', 'FINANCIAL', 'SURVEILLANCE', 'SOCIAL_MEDIA', 'CRIMINAL_HISTORY', 'INTEL', name='document_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('derived_key', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('ingestion_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', 'QUARANTINED', name='ingestion_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ingestion_stage', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('source_confidence', sa.Enum('VERIFIED', 'UNVERIFIED', 'ANONYMOUS_TIP', name='source_confidence', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete only — no row is ever physically removed'),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_case_documents_ck_case_documents_retry_nonneg')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_documents_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_case_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_documents')),
    sa.UniqueConstraint('case_id', 'content_hash', name='uq_case_documents_case_hash')
    )
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_documents_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_documents_case_id'))

    op.drop_table('case_documents')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('jurisdiction_access_requests')
    with op.batch_alter_table('entity_resolution_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_resolution_queue_case_id'))

    op.drop_table('entity_resolution_queue')
    with op.batch_alter_table('detected_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detected_patterns_case_id'))

    op.drop_table('detected_patterns')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_jurisdiction_id'))

    op.drop_table('cases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_jurisdiction')

    op.drop_table('users')
    op.drop_table('pattern_config')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_doc_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_case_id'))

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('document_stage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_stage_events_doc_id'))
        batch_op.drop_index(batch_op.f('ix_document_stage_events_case_id'))

    op.drop_table('document_stage_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_timestamp')
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))

    op.drop_table('audit_logs')
    op.drop_table('audit_chain_head')
    op.drop_table('audit_anchors')
    # ### end Alembic commands ###
