"""Regenerate the CrimeLink external synthetic corpus (v2).

The previous corpus was generated by drawing mostly-random rows and leaving
~70% of CDR / transaction / sighting / intel records without a ``case_id``.
That produced exactly the artefact the reviewer flagged: the ingestion
pipeline had no coherent story to attach rows to, so the graph filled up with
dangling "negatives" that meant nothing.

This generator rebuilds the corpus around two explicit populations:

* **Case population** — every event row belongs to a named case and references
  entities (people, phones, vehicles, accounts, locations) that are actually
  members of that case.  Rows carry an explicit ``case_id``.
* **Background population** — a smaller, self-contained social circle of
  people who are *not* members of any case.  Their calls and transfers are
  internally coherent (they phone and pay each other), but they carry no
  ``case_id`` and are the "unrelated" negative class.  The source adapter
  quarantines them with the honest reason ``subject_in_no_case`` — real,
  unrelated people, not garbage.

Everything is deterministic (``random.Random(seed)``) so the corpus can be
rebuilt identically.  Only the standard library is used, so the generator runs
without the application's dependencies.

Run from the backend directory:

    python3 app/synthetic_corpus/build_external.py

The output replaces ``backend/CrimeLink_Synthetic_Corpus_v1``.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import shutil
from datetime import datetime, timedelta
from pathlib import Path

# ---------------------------------------------------------------------------
# Determinism + configuration
# ---------------------------------------------------------------------------

DEFAULT_SEED = 20260902

BACKEND_DIR = Path(__file__).resolve().parents[2]
CORPUS_ROOT = BACKEND_DIR / "CrimeLink_Synthetic_Corpus_v1"

OPERATIONAL_DIR = "operational"
DOCUMENTS_DIR = "documents"
GROUND_TRUTH_DIR = "ground_truth"
METADATA_DIR = "metadata"

N_CASES = 12
PERSONS_PER_CASE = 8
BACKGROUND_PERSONS = 24

# Synthetic name pools — generated combinations, never real people.
FIRST_NAMES = [
    "Aarav", "Ananya", "Arjun", "Bhavna", "Chetan", "Deepika", "Dev", "Divya",
    "Gaurav", "Ishaan", "Kavya", "Lakshmi", "Manoj", "Meera", "Nikhil", "Nisha",
    "Pranav", "Priya", "Rahul", "Rani", "Rohit", "Sanya", "Sanjay", "Sneha",
    "Tanvi", "Vikram", "Yash", "Zoya",
]
LAST_NAMES = [
    "Acharya", "Babu", "Bhat", "Chauhan", "Das", "Goud", "Hegde", "Iyer",
    "Joshi", "Kulkarni", "Mishra", "Nair", "Patil", "Pillai", "Rao", "Reddy",
    "Saxena", "Sharma", "Singh", "Verma", "Yadav",
]

GENDERS = ["M", "F"]
STATES = ["Andhra Pradesh", "Karnataka", "Maharashtra", "Rajasthan", "Telangana"]
CITIES = {
    "Andhra Pradesh": ["Visakhapatnam", "Kurnool", "Vijayawada"],
    "Karnataka": ["Bengaluru", "Mysuru", "Hubballi"],
    "Maharashtra": ["Pune", "Nagpur", "Nashik"],
    "Rajasthan": ["Jaipur", "Kota", "Udaipur"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad"],
}

LOCATION_NAMES = [
    "Warehouse", "Petrol Pump", "Bus Stand", "Railway Station", "Market",
    "Industrial Area", "Highway Junction", "Hotel", "Checkpost", "Toll Plaza",
]
ORG_SUFFIXES = ["Traders", "Logistics", "Finances", "Constructions", "Exports", "Transport"]

BANK_CODES = ["HDFC", "SBI", "ICICI", "AXIS", "PNB", "KOTAK"]
CALL_TYPES = ["VOICE", "SMS", "DATA"]
TX_TYPES = ["IMPS", "NEFT", "RTGS", "CASH_DEPOSIT", "UPI"]
SIGHTING_SOURCES = ["CCTV", "PATROL", "ANPR", "INTELLIGENCE"]
INTEL_SOURCES = ["FIELD_NOTE", "SOURCE_REPORT", "SURVEILLANCE_NOTE", "TIP"]
VEHICLE_TYPES = ["HATCHBACK", "SEDAN", "SUV", "MOTORCYCLE", "PICKUP"]
VEHICLE_COLORS = ["White", "Silver", "Black", "Red", "Blue", "Grey"]
CASE_TYPES = ["MURDER", "ROBBERY", "KIDNAPPING", "EXTORTION", "FINANCIAL_FRAUD", "THEFT"]

ROLES = ["SUSPECT", "ACCOMPLICE", "VICTIM", "WITNESS"]
STATUS_PERSON = ["ACTIVE", "ACTIVE", "ACTIVE", "UNDER_INVESTIGATION"]

PLATE_STATES = ["AP", "KA", "MH", "RJ", "TS"]


# ---------------------------------------------------------------------------
# Small deterministic helpers
# ---------------------------------------------------------------------------


def pad_phone(rng: random.Random, existing: set[str]) -> str:
    while True:
        number = "9" + str(rng.randint(1, 9)) + "".join(str(rng.randint(0, 9)) for _ in range(8))
        if number not in existing:
            existing.add(number)
            return number


def pad_plate(rng: random.Random, existing: set[str]) -> str:
    while True:
        plate = (
            rng.choice(PLATE_STATES)
            + f"{rng.randint(10, 99):02d}"
            + "".join(rng.choice("ABCDEFGHJKLMNPQRSTUVWXYZ") for _ in range(2))
            + f"{rng.randint(1000, 9999):04d}"
        )
        if plate not in existing:
            existing.add(plate)
            return plate


def pad_account(rng: random.Random, existing: set[str]) -> str:
    while True:
        number = "".join(str(rng.randint(0, 9)) for _ in range(12))
        if number not in existing:
            existing.add(number)
            return number


def iso(rng: random.Random, start: datetime, end: datetime) -> str:
    delta = (end - start).total_seconds()
    return (start + timedelta(seconds=rng.uniform(0, delta))).strftime("%Y-%m-%d %H:%M:%S")


# ---------------------------------------------------------------------------
# Corpus model
# ---------------------------------------------------------------------------


class Builder:
    def __init__(self, seed: int, root: Path | None = None) -> None:
        self.rng = random.Random(seed)
        self.seed = seed
        # Where the corpus is written.  Defaults to the repository-local corpus
        # directory; callers (tests) may override it to write elsewhere.
        self.root = root or CORPUS_ROOT

        self.persons: list[dict] = []
        self.phones: list[dict] = []
        self.vehicles: list[dict] = []
        self.accounts: list[dict] = []
        self.locations: list[dict] = []
        self.organizations: list[dict] = []
        self.case_members: list[dict] = []
        self.person_orgs: list[dict] = []
        self.cases: list[dict] = []
        self.cdr: list[dict] = []
        self.transactions: list[dict] = []
        self.sightings: list[dict] = []
        self.intel: list[dict] = []
        self.documents: list[dict] = []

        self.used_names: set[str] = set()
        self.used_phones: set[str] = set()
        self.used_plates: set[str] = set()
        self.used_accounts: set[str] = set()

        # ground truth accumulators
        self.gt_relationships: list[dict] = []
        self.gt_money_cycles: list[dict] = []
        self.gt_hidden_networks: list[dict] = []
        self.gt_bridge_people: list[dict] = []
        self.gt_anomalies: list[dict] = []

        self._seq = 0
        self._case_persons: dict[str, list[dict]] = {}
        self._doc_texts: dict[str, str] = {}

    # ---- ids ----------------------------------------------------------------
    def nid(self, prefix: str) -> str:
        self._seq += 1
        return f"{prefix}{self._seq:04d}"

    # ---- population builders -------------------------------------------------
    def _make_person(self, city: str, state: str, status: str | None = None) -> dict:
        while True:
            name = f"{self.rng.choice(FIRST_NAMES)} {self.rng.choice(LAST_NAMES)}"
            if name not in self.used_names:
                self.used_names.add(name)
                break
        return {
            "person_id": self.nid("P"),
            "full_name": name,
            "gender": self.rng.choice(GENDERS),
            "dob": f"{self.rng.randint(1960, 2002)}-{self.rng.randint(1, 12):02d}-{self.rng.randint(1, 28):02d}",
            "address": f"{self.rng.randint(1, 200)} {self.rng.choice(['MG Road', 'Station Road', 'Market Street', 'Gandhi Nagar'])}",
            "city": city,
            "state": state,
            "status": status or self.rng.choice(STATUS_PERSON),
        }

    def _make_phone(self, person_id: str, source: str) -> dict:
        return {
            "phone_id": self.nid("PH"),
            "phone_number": pad_phone(self.rng, self.used_phones),
            "owner_person_id": person_id,
            "status": "ACTIVE",
            "source": source,
        }

    def _make_vehicle(self, person_id: str) -> dict:
        return {
            "vehicle_id": self.nid("V"),
            "registration_number": pad_plate(self.rng, self.used_plates),
            "vehicle_type": self.rng.choice(VEHICLE_TYPES),
            "owner_person_id": person_id,
            "color": self.rng.choice(VEHICLE_COLORS),
        }

    def _make_account(self, person_id: str) -> dict:
        return {
            "account_id": self.nid("AC"),
            "account_number": pad_account(self.rng, self.used_accounts),
            "holder_person_id": person_id,
            "bank_code": self.rng.choice(BANK_CODES),
            "account_status": "ACTIVE",
        }

    def _make_location(self, city: str, state: str) -> dict:
        return {
            "location_id": self.nid("L"),
            "name": f"{self.rng.choice(LOCATION_NAMES)} {self.rng.randint(1, 30)}",
            "city": city,
            "state": state,
            "latitude": f"{self.rng.uniform(8.0, 28.0):.6f}",
            "longitude": f"{self.rng.uniform(68.0, 96.0):.6f}",
        }

    def _make_org(self, city: str, state: str) -> dict:
        return {
            "organization_id": self.nid("ORG"),
            "name": f"{self.rng.choice(LAST_NAMES)} {self.rng.choice(ORG_SUFFIXES)}",
            "organization_type": self.rng.choice(["PRIVATE", "LOGISTICS", "FINANCE"]),
            "city": city,
            "state": state,
        }

    # ---- case + background ---------------------------------------------------
    def build_case(self, index: int) -> dict:
        state = self.rng.choice(STATES)
        city = self.rng.choice(CITIES[state])
        registered = datetime(2024, 1, 1) + timedelta(days=self.rng.randint(0, 540))
        case_id = f"C{index:04d}"
        case = {
            "case_id": case_id,
            "case_number": f"FIR/{registered.year}/{index:05d}",
            "registered_date": registered.strftime("%Y-%m-%d"),
            "case_type": self.rng.choice(CASE_TYPES),
            "police_station": f"PS-{index:02d}",
            "city": city,
            "status": "ACTIVE",
        }
        self.cases.append(case)

        members: list[dict] = []
        # 6 case locations + 1-2 organisations shared by the case's people.
        case_locations = [self._make_location(city, state) for _ in range(6)]
        self.locations.extend(case_locations)
        orgs = [self._make_org(city, state) for _ in range(self.rng.choice([1, 2]))]
        self.organizations.extend(orgs)

        for _ in range(PERSONS_PER_CASE):
            person = self._make_person(city, state)
            self.persons.append(person)
            member = {
                "case_member_id": self.nid("CM"),
                "case_id": case_id,
                "person_id": person["person_id"],
                "role": self.rng.choice(ROLES),
            }
            self.case_members.append(member)
            members.append({"person": person, "member": member})

            # Assets: every member has a phone; most have a vehicle; most have
            # an account.  Assignments are per-case coherent.
            self.phones.append(self._make_phone(person["person_id"], "corpus"))
            if self.rng.random() < 0.6:
                self.vehicles.append(self._make_vehicle(person["person_id"]))
            if self.rng.random() < 0.8:
                self.accounts.append(self._make_account(person["person_id"]))
            if orgs and self.rng.random() < 0.5:
                self.person_orgs.append(
                    {
                        "person_org_id": self.nid("PO"),
                        "person_id": person["person_id"],
                        "organization_id": orgs[0]["organization_id"],
                        "role": self.rng.choice(["OWNER", "EMPLOYEE", "DIRECTOR"]),
                        "start_date": "",
                        "end_date": "",
                    }
                )

        self._case_persons[case_id] = members

        # --- coherent case events (all with explicit case_id) -----------------
        end = registered + timedelta(days=365)
        start = registered - timedelta(days=90)

        person_ids = [m["person"]["person_id"] for m in members]
        phones_by_person: dict[str, str] = {
            ph["owner_person_id"]: ph["phone_id"]
            for ph in self.phones
            if ph["owner_person_id"] in set(person_ids)
        }

        # CDR: calls among case members' phones.
        for _ in range(35):
            a = self.rng.choice(person_ids)
            b = self.rng.choice(person_ids)
            if a == b:
                continue
            self.cdr.append(
                {
                    "cdr_id": self.nid("CDR"),
                    "timestamp": iso(self.rng, start, end),
                    "from_phone_id": phones_by_person[a],
                    "to_phone_id": phones_by_person[b],
                    "duration_seconds": str(self.rng.randint(5, 3600)),
                    "call_type": self.rng.choice(CALL_TYPES),
                    "cell_location_id": self.rng.choice(case_locations)["location_id"],
                    "case_id": case_id,
                }
            )
            self.gt_relationships.append(
                {
                    "relationship_id": self.nid("GR"),
                    "source_person_id": a,
                    "target_person_id": b,
                    "relationship_type": "COMMUNICATION",
                    "network_id": f"N{index:02d}",
                }
            )

        # Transfers: among case members' accounts.
        account_ids = [acc["account_id"] for acc in self.accounts if acc["holder_person_id"] in person_ids]
        accounts_by_person = {m["person"]["person_id"]: next((acc["account_id"] for acc in self.accounts if acc["holder_person_id"] == m["person"]["person_id"]), None) for m in members}
        for _ in range(15):
            a = self.rng.choice(person_ids)
            b = self.rng.choice(person_ids)
            if a == b:
                continue
            fa, ta = accounts_by_person.get(a), accounts_by_person.get(b)
            if not fa or not ta:
                continue
            self.transactions.append(
                {
                    "transaction_id": self.nid("TX"),
                    "timestamp": iso(self.rng, start, end),
                    "from_account_id": fa,
                    "to_account_id": ta,
                    "amount_inr": f"{self.rng.randint(5000, 500000):.2f}",
                    "transaction_type": self.rng.choice(TX_TYPES),
                    "location_id": self.rng.choice(case_locations)["location_id"],
                    "case_id": case_id,
                }
            )
            self.gt_relationships.append(
                {
                    "relationship_id": self.nid("GR"),
                    "source_person_id": a,
                    "target_person_id": b,
                    "relationship_type": "FINANCIAL",
                    "network_id": f"N{index:02d}",
                }
            )

        # Sightings: case vehicles observed at case locations.
        case_vehicles = [v["vehicle_id"] for v in self.vehicles if v["owner_person_id"] in person_ids]
        for _ in range(10):
            if not case_vehicles:
                break
            self.sightings.append(
                {
                    "sighting_id": self.nid("VS"),
                    "vehicle_id": self.rng.choice(case_vehicles),
                    "location_id": self.rng.choice(case_locations)["location_id"],
                    "timestamp": iso(self.rng, start, end),
                    "case_id": case_id,
                    "source": self.rng.choice(SIGHTING_SOURCES),
                }
            )

        # Intel reports: about case members.
        for _ in range(5):
            self.intel.append(
                {
                    "report_id": self.nid("IR"),
                    "report_date": iso(self.rng, start, end)[:10],
                    "subject_person_id": self.rng.choice(person_ids),
                    "location_id": self.rng.choice(case_locations)["location_id"],
                    "case_id": case_id,
                    "source_type": self.rng.choice(INTEL_SOURCES),
                    "summary": f"Field report regarding {self.rng.choice(person_ids)} activity near {self.rng.choice(case_locations)['name']}.",
                }
            )

        # --- documents (FIR note + intel note) ---------------------------------
        doc_fir = self.nid("DOC")
        doc_intel = self.nid("DOC")
        fir_text = self._render_fir(case, members, case_locations)
        intel_text = self._render_intel(case, members, case_locations)
        self.documents.append(
            {
                "document_id": doc_fir,
                "case_id": case_id,
                "document_type": "FIR",
                "file_path": f"documents/{doc_fir}.txt",
                "language": "en",
                "source_environment": "synthetic",
            }
        )
        self.documents.append(
            {
                "document_id": doc_intel,
                "case_id": case_id,
                "document_type": "INTEL",
                "file_path": f"documents/{doc_intel}.txt",
                "language": "en",
                "source_environment": "synthetic",
            }
        )
        self._doc_texts[doc_fir] = fir_text
        self._doc_texts[doc_intel] = intel_text

        # Hidden network + one bridge person per pair of consecutive cases.
        self.gt_hidden_networks.append(
            {"network_id": f"N{index:02d}", "case_id": case_id, "members": person_ids[:]}
        )
        if index >= 2:
            self.gt_bridge_people.append(
                {
                    "person_id": person_ids[0],
                    "network_a": f"N{index - 1:02d}",
                    "network_b": f"N{index:02d}",
                }
            )
        # Money cycle: a -> b -> c -> a among three case accounts.
        trio = [p for p in person_ids if accounts_by_person.get(p)][:3]
        if len(trio) == 3:
            self.gt_money_cycles.append(
                {
                    "cycle_id": self.nid("MC"),
                    "case_id": case_id,
                    "accounts": [accounts_by_person[p] for p in trio],
                    "note": "Circular transfer chain among case accounts.",
                }
            )
        return case

    def build_background(self) -> None:
        """A coherent, self-contained *unrelated* population (the negative class)."""
        for _ in range(BACKGROUND_PERSONS):
            state = self.rng.choice(STATES)
            city = self.rng.choice(CITIES[state])
            person = self._make_person(city, state, status="ACTIVE")
            self.persons.append(person)
            self.phones.append(self._make_phone(person["person_id"], "corpus"))
            if self.rng.random() < 0.5:
                self.vehicles.append(self._make_vehicle(person["person_id"]))
            if self.rng.random() < 0.7:
                self.accounts.append(self._make_account(person["person_id"]))

        bg_ids = [p["person_id"] for p in self.persons[-BACKGROUND_PERSONS:]]
        phones_by_person = {
            p["person_id"]: next(
                ph["phone_id"] for ph in self.phones if ph["owner_person_id"] == p["person_id"]
            )
            for p in self.persons
            if p["person_id"] in bg_ids
        }
        accounts_by_person = {
            ac["holder_person_id"]: ac["account_id"]
            for ac in self.accounts
            if ac["holder_person_id"] in set(bg_ids)
        }
        for _ in range(40):
            a = self.rng.choice(bg_ids)
            b = self.rng.choice(bg_ids)
            if a == b:
                continue
            self.cdr.append(
                {
                    "cdr_id": self.nid("CDR"),
                    "timestamp": iso(self.rng, datetime(2024, 1, 1), datetime(2025, 12, 31)),
                    "from_phone_id": phones_by_person[a],
                    "to_phone_id": phones_by_person[b],
                    "duration_seconds": str(self.rng.randint(5, 1800)),
                    "call_type": self.rng.choice(CALL_TYPES),
                    "cell_location_id": "",
                    "case_id": "",
                }
            )
        for _ in range(15):
            a = self.rng.choice(list(accounts_by_person))
            b = self.rng.choice(list(accounts_by_person))
            if a == b:
                continue
            self.transactions.append(
                {
                    "transaction_id": self.nid("TX"),
                    "timestamp": iso(self.rng, datetime(2024, 1, 1), datetime(2025, 12, 31)),
                    "from_account_id": accounts_by_person[a],
                    "to_account_id": accounts_by_person[b],
                    "amount_inr": f"{self.rng.randint(1000, 200000):.2f}",
                    "transaction_type": self.rng.choice(TX_TYPES),
                    "location_id": "",
                    "case_id": "",
                }
            )

    # ---- documents -----------------------------------------------------------
    def _render_fir(self, case: dict, members: list[dict], locations: list[dict]) -> str:
        names = [m["person"]["full_name"] for m in members]
        loc = locations[0]["name"] if locations else "the district"
        return (
            f"Case Reference: {case['case_number']}\n"
            f"Police Station: {case['police_station']}\n"
            f"Date: {case['registered_date']}\n\n"
            f"First Information Report\n"
            f"Complainant states that an offence of {case['case_type']} occurred in "
            f"{case['city']}, {case['police_station']} jurisdiction.\n"
            f"Persons named in the complaint: {', '.join(names[:5])}.\n"
            f"Initial field activity was recorded near {loc}.\n"
            f"These observations are leads and require corroboration.\n"
        )

    def _render_intel(self, case: dict, members: list[dict], locations: list[dict]) -> str:
        names = [m["person"]["full_name"] for m in members]
        loc = locations[1]["name"] if len(locations) > 1 else "the district"
        return (
            f"Intelligence note — {case['case_number']}\n"
            f"Source observation dated {self.rng.choice(['2024', '2025'])}.\n\n"
            f"Confidential reporting places {names[0] if names else 'a subject'} in "
            f"repeated contact with other members of this group around {loc}.\n"
            f"Associates referenced include: {', '.join(names[1:4])}.\n"
            f"Treat as uncorroborated intelligence pending further checks.\n"
        )

    # ---- write phase ---------------------------------------------------------
    def write(self) -> None:
        root = self.root
        if root.exists():
            shutil.rmtree(root)
        (root / OPERATIONAL_DIR).mkdir(parents=True, exist_ok=True)
        (root / DOCUMENTS_DIR).mkdir(parents=True, exist_ok=True)
        (root / GROUND_TRUTH_DIR).mkdir(parents=True, exist_ok=True)
        (root / METADATA_DIR).mkdir(parents=True, exist_ok=True)

        def write_csv(name: str, rows: list[dict], fields: list[str]) -> None:
            path = root / OPERATIONAL_DIR / name
            with path.open("w", newline="", encoding="utf-8") as fh:
                writer = csv.DictWriter(fh, fieldnames=fields)
                writer.writeheader()
                for row in rows:
                    writer.writerow({k: row.get(k, "") for k in fields})

        write_csv(
            "cases.csv", self.cases,
            ["case_id", "case_number", "registered_date", "case_type", "police_station", "city", "status"],
        )
        write_csv(
            "persons.csv", self.persons,
            ["person_id", "full_name", "gender", "dob", "address", "city", "state", "status"],
        )
        write_csv(
            "phones.csv", self.phones,
            ["phone_id", "phone_number", "owner_person_id", "status", "source"],
        )
        write_csv(
            "vehicles.csv", self.vehicles,
            ["vehicle_id", "registration_number", "vehicle_type", "owner_person_id", "color"],
        )
        write_csv(
            "accounts.csv", self.accounts,
            ["account_id", "account_number", "holder_person_id", "bank_code", "account_status"],
        )
        write_csv(
            "locations.csv", self.locations,
            ["location_id", "name", "city", "state", "latitude", "longitude"],
        )
        write_csv(
            "organizations.csv", self.organizations,
            ["organization_id", "name", "organization_type", "city", "state"],
        )
        write_csv(
            "case_members.csv", self.case_members,
            ["case_member_id", "case_id", "person_id", "role"],
        )
        write_csv(
            "person_organizations.csv", self.person_orgs,
            ["person_org_id", "person_id", "organization_id", "role", "start_date", "end_date"],
        )
        write_csv(
            "cdr.csv", self.cdr,
            ["cdr_id", "timestamp", "from_phone_id", "to_phone_id", "duration_seconds", "call_type", "cell_location_id", "case_id"],
        )
        write_csv(
            "transactions.csv", self.transactions,
            ["transaction_id", "timestamp", "from_account_id", "to_account_id", "amount_inr", "transaction_type", "location_id", "case_id"],
        )
        write_csv(
            "vehicle_sightings.csv", self.sightings,
            ["sighting_id", "vehicle_id", "location_id", "timestamp", "case_id", "source"],
        )
        write_csv(
            "intelligence_reports.csv", self.intel,
            ["report_id", "report_date", "subject_person_id", "location_id", "case_id", "source_type", "summary"],
        )
        write_csv(
            "documents.csv", self.documents,
            ["document_id", "case_id", "document_type", "file_path", "language", "source_environment"],
        )

        for doc in self.documents:
            text = self._doc_texts.get(doc["document_id"], "")
            (root / doc["file_path"]).write_text(text, encoding="utf-8")

        # Ground truth — evaluation only, never ingested into investigator view.
        def write_json(name: str, payload: list) -> None:
            (root / GROUND_TRUTH_DIR / name).write_text(
                json.dumps(payload, indent=2), encoding="utf-8"
            )

        write_json("relationship_ground_truth.json", self.gt_relationships)
        write_json("hidden_networks.json", self.gt_hidden_networks)
        write_json("money_cycles.json", self.gt_money_cycles)
        write_json("bridge_people.json", self.gt_bridge_people)
        write_json(
            "anomaly_events.json",
            [
                {
                    "anomaly_id": self.nid("AN"),
                    "case_id": self.cases[0]["case_id"],
                    "kind": "large_single_transfer",
                    "description": "A single transfer far above the case median, flagged for review.",
                }
            ],
        )

        # Metadata.
        config = {
            "dataset_version": "2.0",
            "seed": self.seed,
            "profile": "medium",
            "cases": len(self.cases),
            "persons": len(self.persons),
            "background_persons": BACKGROUND_PERSONS,
            "phones": len(self.phones),
            "vehicles": len(self.vehicles),
            "accounts": len(self.accounts),
            "locations": len(self.locations),
            "organizations": len(self.organizations),
            "cdr": len(self.cdr),
            "transactions": len(self.transactions),
            "vehicle_sightings": len(self.sightings),
            "intelligence_reports": len(self.intel),
            "documents": len(self.documents),
            "negative_class": "background_population_unrelated",
        }
        (root / METADATA_DIR / "generation_config.json").write_text(
            json.dumps(config, indent=2), encoding="utf-8"
        )
        (root / METADATA_DIR / "schema.json").write_text(
            json.dumps(
                {
                    "structured_sources": "CSV",
                    "unstructured_sources": ["TXT"],
                    "metadata": "JSON",
                    "ground_truth": "JSON (isolated)",
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        (root / "README.md").write_text(
            "".join(
                [
                    "# CrimeLink Synthetic Corpus v2\n\n",
                    "100% synthetic development/evaluation corpus. Not government/police data.\n\n",
                    "Two populations: case population (every event row references its case's ",
                    "members) and a self-contained background population whose rows carry no ",
                    "`case_id` — the coherent 'unrelated' negative class. Ground truth is ",
                    "benchmark-only and never ingested into investigator-facing storage.\n\n",
                    f"Seed: {self.seed}\n",
                ]
            ),
            encoding="utf-8",
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate the CrimeLink external corpus.")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--cases", type=int, default=N_CASES)
    parser.add_argument("--background", type=int, default=BACKGROUND_PERSONS)
    args = parser.parse_args()

    builder = Builder(args.seed)
    for index in range(1, args.cases + 1):
        builder.build_case(index)
    builder.build_background()
    builder.write()

    print(f"Corpus written to {builder.root}")
    print(f"  cases={len(builder.cases)} persons={len(builder.persons)} "
          f"background={BACKGROUND_PERSONS}")
    print(f"  cdr={len(builder.cdr)} transactions={len(builder.transactions)} "
          f"sightings={len(builder.sightings)} intel={len(builder.intel)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
